name: Build and Copy to Portfolio

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout punch in page
        uses: actions/Checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: npm ci

      - name: Build punch in
        run: npm run build

      - name: clone Portfolio repo
        run: git clone https://${{ secrets.PORTFOLIO_REPO_TOKEN }}@github.com/samdeitz/personal-portfolio.git

      - name: Install portfolio dependencies
        run: |
          cd personal-portfolio
          npm ci

      - name: copy build to portfolio
        run: |
              rm -rf personal-portfolio/public/md-punch-in
              mkdir -p personal-portfolio/public/md-punch-in
              cp -r dist/* personal-portfolio/public/md-punch-in

      - name: configure git for commit and deploy
        run: |
              git config --global user.name "punch-in-bot"
              git config --global user.email "punch-in-bot@github.com"      

      - name: commit & push
        run: |
              cd personal-portfolio
              git add public/md-punch-in
              git commit -m "Update punch in build" || exit 0
              git push

      - name: deploy portfolio
        env:
          GH_TOKEN: ${{ secrets.PORTFOLIO_REPO_TOKEN }}
        run: |
          cd personal-portfolio
          npm run predeploy
          npm run deploy